name: CvMatcher
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2024.9.24
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.9.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - certifi==2024.8.30
      - colorama==0.4.6
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.10
      - jsonpath-python==1.0.6
      - mistralai==1.1.0
      - mypy-extensions==1.0.0
      - packaging==24.1
      - pdf2image==1.17.0
      - pillow==11.0.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pypdf2==3.0.1
      - pytesseract==0.3.13
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - six==1.16.0
      - sniffio==1.3.1
      - tqdm==4.66.6
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
